# Generated by Django 2.2.6 on 2020-08-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
