# Generated by Django 2.2.6 on 2020-08-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20200814_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
    ]
