# Generated by Django 2.2.6 on 2020-08-08 07:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnitures', '0002_auto_20200804_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='picture',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
