# Generated by Django 2.2.6 on 2020-08-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitures', '0003_furniture_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='furniture',
            name='tags',
            field=models.ManyToManyField(to='furnitures.Tag'),
        ),
    ]
