# Generated by Django 2.2.6 on 2020-08-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitures', '0004_auto_20200809_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='cost',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=10),
            preserve_default=False,
        ),
    ]
