# Generated by Django 2.2.6 on 2020-08-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitures', '0006_auto_20200809_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
