# Generated by Django 2.2.6 on 2020-08-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitures', '0007_auto_20200809_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='color',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='furniture',
            name='materials',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='furniture',
            name='weight',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
