# Generated by Django 2.2.6 on 2020-08-15 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnitures', '0008_auto_20200815_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furniture',
            name='color',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='weight',
        ),
    ]
