# Generated by Django 2.2.6 on 2020-08-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitures', '0009_auto_20200815_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='breath',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='height',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='length',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='quantity',
            field=models.IntegerField(blank=True),
        ),
    ]
