# Generated by Django 2.2.6 on 2020-08-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitures', '0010_auto_20200815_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='color',
            field=models.CharField(default='red', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='furniture',
            name='materials',
            field=models.CharField(default='wood', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='furniture',
            name='weight',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='furniture',
            name='breath',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
